# Generated by Django 5.2.2 on 2025-08-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
